language: php
php:
    - '7.0'
    - '7.1'

before_script:
    - php composer.phar install

script:
    - phpunit --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml.dist tests

after_script:

