language: php
php:
    - '7.0'
    - '7.1'

before_script:
    - php composer.phar install --dev --prefer-source

script:
    - phpunit --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml.dist tests

after_script:
    - php vendor/bin/coveralls -v
